// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OakIdeas.Aspire.DataExplorer.Sample.Api.Data;

#nullable disable

namespace OakIdeas.Aspire.DataExplorer.Sample.Api.MigrationsWarehouse
{
    [DbContext(typeof(WarehouseDbContext))]
    partial class WarehouseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OakIdeas.Aspire.DataExplorer.Sample.Api.Data.WarehouseInventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("LastRestockedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("int");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal>("StandardCost")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.HasIndex("SupplierId", "Name");

                    b.ToTable("InventoryItems", t =>
                        {
                            t.HasCheckConstraint("CK_WarehouseInventoryItems_ReorderLevel", "[ReorderLevel] >= 0");

                            t.HasCheckConstraint("CK_WarehouseInventoryItems_StandardCost", "[StandardCost] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastRestockedAt = new DateTimeOffset(new DateTime(2026, 2, 4, 14, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Stackable storage bin",
                            ReorderLevel = 40,
                            Sku = "BIN-STACK-001",
                            StandardCost = 14.50m,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 2,
                            LastRestockedAt = new DateTimeOffset(new DateTime(2026, 2, 7, 9, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Handheld barcode scanner",
                            ReorderLevel = 8,
                            Sku = "SCAN-HAND-002",
                            StandardCost = 89.00m,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 3,
                            LastRestockedAt = new DateTimeOffset(new DateTime(2026, 2, 2, 11, 15, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Thermal label refill pack",
                            ReorderLevel = 25,
                            Sku = "LABEL-THERM-003",
                            StandardCost = 32.75m,
                            SupplierId = 2
                        });
                });

            modelBuilder.Entity("OakIdeas.Aspire.DataExplorer.Sample.Api.Data.WarehouseLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsClimateControlled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("RegionCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("WarehouseLocations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsClimateControlled = true,
                            Name = "Seattle Fulfillment",
                            RegionCode = "US-WEST"
                        },
                        new
                        {
                            Id = 2,
                            IsClimateControlled = false,
                            Name = "Austin Overflow",
                            RegionCode = "US-CENTRAL"
                        });
                });

            modelBuilder.Entity("OakIdeas.Aspire.DataExplorer.Sample.Api.Data.WarehouseStockBin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BinCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("InventoryItemId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastCountedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("QuantityOnHand")
                        .HasColumnType("int");

                    b.Property<int>("WarehouseLocationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId", "WarehouseLocationId");

                    b.HasIndex("WarehouseLocationId", "BinCode")
                        .IsUnique();

                    b.ToTable("StockBins", t =>
                        {
                            t.HasCheckConstraint("CK_WarehouseStockBins_QuantityOnHand", "[QuantityOnHand] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BinCode = "SEA-A01",
                            InventoryItemId = 1,
                            LastCountedAt = new DateTimeOffset(new DateTime(2026, 2, 8, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            QuantityOnHand = 128,
                            WarehouseLocationId = 1
                        },
                        new
                        {
                            Id = 2,
                            BinCode = "SEA-B07",
                            InventoryItemId = 2,
                            LastCountedAt = new DateTimeOffset(new DateTime(2026, 2, 8, 8, 20, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            QuantityOnHand = 18,
                            WarehouseLocationId = 1
                        },
                        new
                        {
                            Id = 3,
                            BinCode = "AUS-C03",
                            InventoryItemId = 3,
                            LastCountedAt = new DateTimeOffset(new DateTime(2026, 2, 8, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            QuantityOnHand = 64,
                            WarehouseLocationId = 2
                        },
                        new
                        {
                            Id = 4,
                            BinCode = "AUS-A02",
                            InventoryItemId = 1,
                            LastCountedAt = new DateTimeOffset(new DateTime(2026, 2, 8, 9, 15, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            QuantityOnHand = 42,
                            WarehouseLocationId = 2
                        });
                });

            modelBuilder.Entity("OakIdeas.Aspire.DataExplorer.Sample.Api.Data.WarehouseSupplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsPreferred")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("ContactEmail")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactEmail = "ops@northwind.example",
                            IsPreferred = true,
                            Name = "Northwind Storage"
                        },
                        new
                        {
                            Id = 2,
                            ContactEmail = "inventory@blueyonder.example",
                            IsPreferred = false,
                            Name = "Blue Yonder Parts"
                        });
                });

            modelBuilder.Entity("OakIdeas.Aspire.DataExplorer.Sample.Api.Data.WarehouseInventoryItem", b =>
                {
                    b.HasOne("OakIdeas.Aspire.DataExplorer.Sample.Api.Data.WarehouseSupplier", "Supplier")
                        .WithMany("InventoryItems")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("OakIdeas.Aspire.DataExplorer.Sample.Api.Data.WarehouseStockBin", b =>
                {
                    b.HasOne("OakIdeas.Aspire.DataExplorer.Sample.Api.Data.WarehouseInventoryItem", "InventoryItem")
                        .WithMany("StockBins")
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OakIdeas.Aspire.DataExplorer.Sample.Api.Data.WarehouseLocation", "WarehouseLocation")
                        .WithMany("StockBins")
                        .HasForeignKey("WarehouseLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");

                    b.Navigation("WarehouseLocation");
                });

            modelBuilder.Entity("OakIdeas.Aspire.DataExplorer.Sample.Api.Data.WarehouseInventoryItem", b =>
                {
                    b.Navigation("StockBins");
                });

            modelBuilder.Entity("OakIdeas.Aspire.DataExplorer.Sample.Api.Data.WarehouseLocation", b =>
                {
                    b.Navigation("StockBins");
                });

            modelBuilder.Entity("OakIdeas.Aspire.DataExplorer.Sample.Api.Data.WarehouseSupplier", b =>
                {
                    b.Navigation("InventoryItems");
                });
#pragma warning restore 612, 618
        }
    }
}
