<Project>
  <Target Name="CopyPackagedDataExplorerWebApp"
          AfterTargets="Build"
          Condition="Exists('$(MSBuildThisFileDirectory)dew')">
    <RemoveDir Directories="$(TargetDir)data-explorer-web"
           Condition="Exists('$(TargetDir)data-explorer-web')"
           ContinueOnError="WarnAndContinue" />

    <ItemGroup>
      <_DataExplorerPackagedFiles Include="$(MSBuildThisFileDirectory)dew/**/*" />
      <_DataExplorerPackagedDirectories Include="@(_DataExplorerPackagedFiles->'$(TargetDir)data-explorer-web/%(RecursiveDir)')" />
    </ItemGroup>

    <MakeDir Directories="@(_DataExplorerPackagedDirectories)" />

    <Copy SourceFiles="@(_DataExplorerPackagedFiles)"
      DestinationFiles="@(_DataExplorerPackagedFiles->'$(TargetDir)data-explorer-web/%(RecursiveDir)%(Filename)%(Extension)')"
          SkipUnchangedFiles="false"
          ContinueOnError="WarnAndContinue" />
  </Target>
</Project>
