<Project>
  <ItemGroup>
    <_DataExplorerPackagedFiles Include="$(MSBuildThisFileDirectory)data-explorer-web\**\*" />
  </ItemGroup>

  <Target Name="CopyPackagedDataExplorerWebApp"
          AfterTargets="Build"
          Condition="'@(_DataExplorerPackagedFiles)' != ''">
    <RemoveDir Directories="$(TargetDir)data-explorer-web"
           Condition="Exists('$(TargetDir)data-explorer-web')"
           ContinueOnError="WarnAndContinue" />

    <ItemGroup>
      <_DataExplorerPackagedDirectories Include="@(_DataExplorerPackagedFiles->'$(TargetDir)data-explorer-web\%(RecursiveDir)')" />
    </ItemGroup>

    <MakeDir Directories="@(_DataExplorerPackagedDirectories)" />

    <Copy SourceFiles="@(_DataExplorerPackagedFiles)"
      DestinationFiles="@(_DataExplorerPackagedFiles->'$(TargetDir)data-explorer-web\%(RecursiveDir)%(Filename)%(Extension)')"
          SkipUnchangedFiles="false"
          ContinueOnError="WarnAndContinue" />
  </Target>
</Project>
