// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OakIdeas.Aspire.DataExplorer.Sample.Api.Data;

#nullable disable

namespace OakIdeas.Aspire.DataExplorer.Sample.Api.Migrations
{
    [DbContext(typeof(SampleDbContext))]
    [Migration("20260524091447_ShowcaseProgrammabilityObjects")]
    partial class ShowcaseProgrammabilityObjects
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OakIdeas.Aspire.DataExplorer.Sample.Api.Data.TodoCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasDefaultValue("#64748b");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TodoCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorHex = "#2563eb",
                            IsSystem = true,
                            Name = "Engineering"
                        },
                        new
                        {
                            Id = 2,
                            ColorHex = "#16a34a",
                            IsSystem = false,
                            Name = "Household"
                        },
                        new
                        {
                            Id = 3,
                            ColorHex = "#7c3aed",
                            IsSystem = false,
                            Name = "Learning"
                        });
                });

            modelBuilder.Entity("OakIdeas.Aspire.DataExplorer.Sample.Api.Data.TodoComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("TodoItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TodoItemId", "CreatedAt");

                    b.ToTable("TodoComments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorName = "System",
                            Body = "Kickoff item seeded for demo.",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 10, 9, 10, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            TodoItemId = 1
                        },
                        new
                        {
                            Id = 2,
                            AuthorName = "Sam",
                            Body = "Remember to validate indexes and constraints in DataExplorer.",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 11, 11, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            TodoItemId = 1
                        },
                        new
                        {
                            Id = 3,
                            AuthorName = "Alex",
                            Body = "Blocked waiting for color palette review.",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 12, 10, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            TodoItemId = 3
                        },
                        new
                        {
                            Id = 4,
                            AuthorName = "Taylor",
                            Body = "Errands complete early.",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 13, 12, 5, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            TodoItemId = 4
                        });
                });

            modelBuilder.Entity("OakIdeas.Aspire.DataExplorer.Sample.Api.Data.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset?>("DueAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("TodoCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("TodoListId")
                        .HasColumnType("int");

                    b.Property<byte>("TodoPriorityId")
                        .HasColumnType("tinyint");

                    b.Property<byte>("TodoStatusId")
                        .HasColumnType("tinyint");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TodoCategoryId");

                    b.HasIndex("TodoPriorityId");

                    b.HasIndex("TodoStatusId");

                    b.HasIndex("TodoListId", "TodoStatusId", "DueAt");

                    b.ToTable("TodoItems", t =>
                        {
                            t.HasCheckConstraint("CK_TodoItems_Title_NotBlank", "LEN(LTRIM(RTRIM([Title]))) > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 10, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Add richer schema objects so DataExplorer shows meaningful relationships and constraints.",
                            DueAt = new DateTimeOffset(new DateTime(2026, 1, 15, 17, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsArchived = false,
                            Title = "Instrument sample metadata discovery",
                            TodoCategoryId = 1,
                            TodoListId = 1,
                            TodoPriorityId = (byte)3,
                            TodoStatusId = (byte)2,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 11, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 11, 8, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Document local migration commands and seeded data expectations.",
                            IsArchived = false,
                            Title = "Write migration walkthrough docs",
                            TodoCategoryId = 3,
                            TodoListId = 1,
                            TodoPriorityId = (byte)2,
                            TodoStatusId = (byte)1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 12, 10, 15, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DueAt = new DateTimeOffset(new DateTime(2026, 1, 18, 15, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsArchived = false,
                            Title = "Refactor sample page styles",
                            TodoCategoryId = 1,
                            TodoListId = 1,
                            TodoPriorityId = (byte)2,
                            TodoStatusId = (byte)3
                        },
                        new
                        {
                            Id = 4,
                            CompletedAt = new DateTimeOffset(new DateTime(2026, 1, 13, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 10, 7, 45, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Buy groceries and prep for Monday.",
                            DueAt = new DateTimeOffset(new DateTime(2026, 1, 13, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsArchived = false,
                            Title = "Plan weekend errands",
                            TodoCategoryId = 2,
                            TodoListId = 2,
                            TodoPriorityId = (byte)1,
                            TodoStatusId = (byte)4,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 13, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("OakIdeas.Aspire.DataExplorer.Sample.Api.Data.TodoItemTag", b =>
                {
                    b.Property<int>("TodoItemId")
                        .HasColumnType("int");

                    b.Property<int>("TodoTagId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("TodoItemId", "TodoTagId");

                    b.HasIndex("TodoTagId");

                    b.ToTable("TodoItemTags");

                    b.HasData(
                        new
                        {
                            TodoItemId = 1,
                            TodoTagId = 1,
                            AddedAt = new DateTimeOffset(new DateTime(2026, 1, 10, 9, 5, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            TodoItemId = 1,
                            TodoTagId = 2,
                            AddedAt = new DateTimeOffset(new DateTime(2026, 1, 10, 9, 5, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            TodoItemId = 2,
                            TodoTagId = 3,
                            AddedAt = new DateTimeOffset(new DateTime(2026, 1, 11, 8, 40, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            TodoItemId = 3,
                            TodoTagId = 4,
                            AddedAt = new DateTimeOffset(new DateTime(2026, 1, 12, 10, 20, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            TodoItemId = 3,
                            TodoTagId = 5,
                            AddedAt = new DateTimeOffset(new DateTime(2026, 1, 12, 10, 20, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            TodoItemId = 4,
                            TodoTagId = 2,
                            AddedAt = new DateTimeOffset(new DateTime(2026, 1, 10, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("OakIdeas.Aspire.DataExplorer.Sample.Api.Data.TodoList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TodoLists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 5, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Tasks related to DataExplorer development",
                            IsArchived = false,
                            Name = "Work"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 5, 9, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Personal goals and errands",
                            IsArchived = false,
                            Name = "Personal"
                        });
                });

            modelBuilder.Entity("OakIdeas.Aspire.DataExplorer.Sample.Api.Data.TodoPriority", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<byte>("SortOrder")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TodoPriorities");

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            IsDefault = false,
                            Name = "Low",
                            SortOrder = (byte)1
                        },
                        new
                        {
                            Id = (byte)2,
                            IsDefault = true,
                            Name = "Medium",
                            SortOrder = (byte)2
                        },
                        new
                        {
                            Id = (byte)3,
                            IsDefault = false,
                            Name = "High",
                            SortOrder = (byte)3
                        },
                        new
                        {
                            Id = (byte)4,
                            IsDefault = false,
                            Name = "Critical",
                            SortOrder = (byte)4
                        });
                });

            modelBuilder.Entity("OakIdeas.Aspire.DataExplorer.Sample.Api.Data.TodoStatus", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<byte>("SortOrder")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TodoStatuses");

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            IsClosed = false,
                            Name = "Not Started",
                            SortOrder = (byte)1
                        },
                        new
                        {
                            Id = (byte)2,
                            IsClosed = false,
                            Name = "In Progress",
                            SortOrder = (byte)2
                        },
                        new
                        {
                            Id = (byte)3,
                            IsClosed = false,
                            Name = "Blocked",
                            SortOrder = (byte)3
                        },
                        new
                        {
                            Id = (byte)4,
                            IsClosed = true,
                            Name = "Completed",
                            SortOrder = (byte)4
                        });
                });

            modelBuilder.Entity("OakIdeas.Aspire.DataExplorer.Sample.Api.Data.TodoTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TodoTags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Aspire integration",
                            Name = "aspire"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Entity Framework changes",
                            Name = "ef-core"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Documentation updates",
                            Name = "docs"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Needs immediate attention",
                            Name = "urgent"
                        },
                        new
                        {
                            Id = 5,
                            Description = "API and service work",
                            Name = "backend"
                        });
                });

            modelBuilder.Entity("OakIdeas.Aspire.DataExplorer.Sample.Api.Data.TodoComment", b =>
                {
                    b.HasOne("OakIdeas.Aspire.DataExplorer.Sample.Api.Data.TodoItem", "TodoItem")
                        .WithMany("TodoComments")
                        .HasForeignKey("TodoItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TodoItem");
                });

            modelBuilder.Entity("OakIdeas.Aspire.DataExplorer.Sample.Api.Data.TodoItem", b =>
                {
                    b.HasOne("OakIdeas.Aspire.DataExplorer.Sample.Api.Data.TodoCategory", "TodoCategory")
                        .WithMany("TodoItems")
                        .HasForeignKey("TodoCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OakIdeas.Aspire.DataExplorer.Sample.Api.Data.TodoList", "TodoList")
                        .WithMany("TodoItems")
                        .HasForeignKey("TodoListId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OakIdeas.Aspire.DataExplorer.Sample.Api.Data.TodoPriority", "TodoPriority")
                        .WithMany("TodoItems")
                        .HasForeignKey("TodoPriorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OakIdeas.Aspire.DataExplorer.Sample.Api.Data.TodoStatus", "TodoStatus")
                        .WithMany("TodoItems")
                        .HasForeignKey("TodoStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TodoCategory");

                    b.Navigation("TodoList");

                    b.Navigation("TodoPriority");

                    b.Navigation("TodoStatus");
                });

            modelBuilder.Entity("OakIdeas.Aspire.DataExplorer.Sample.Api.Data.TodoItemTag", b =>
                {
                    b.HasOne("OakIdeas.Aspire.DataExplorer.Sample.Api.Data.TodoItem", "TodoItem")
                        .WithMany("TodoItemTags")
                        .HasForeignKey("TodoItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OakIdeas.Aspire.DataExplorer.Sample.Api.Data.TodoTag", "TodoTag")
                        .WithMany("TodoItemTags")
                        .HasForeignKey("TodoTagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TodoItem");

                    b.Navigation("TodoTag");
                });

            modelBuilder.Entity("OakIdeas.Aspire.DataExplorer.Sample.Api.Data.TodoCategory", b =>
                {
                    b.Navigation("TodoItems");
                });

            modelBuilder.Entity("OakIdeas.Aspire.DataExplorer.Sample.Api.Data.TodoItem", b =>
                {
                    b.Navigation("TodoComments");

                    b.Navigation("TodoItemTags");
                });

            modelBuilder.Entity("OakIdeas.Aspire.DataExplorer.Sample.Api.Data.TodoList", b =>
                {
                    b.Navigation("TodoItems");
                });

            modelBuilder.Entity("OakIdeas.Aspire.DataExplorer.Sample.Api.Data.TodoPriority", b =>
                {
                    b.Navigation("TodoItems");
                });

            modelBuilder.Entity("OakIdeas.Aspire.DataExplorer.Sample.Api.Data.TodoStatus", b =>
                {
                    b.Navigation("TodoItems");
                });

            modelBuilder.Entity("OakIdeas.Aspire.DataExplorer.Sample.Api.Data.TodoTag", b =>
                {
                    b.Navigation("TodoItemTags");
                });
#pragma warning restore 612, 618
        }
    }
}
