<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\OakIdeas.Aspire.DataExplorer.Web.Components\OakIdeas.Aspire.DataExplorer.Web.Components.csproj" />
    <ProjectReference Include="..\OakIdeas.Aspire.DataExplorer.Hosting\OakIdeas.Aspire.DataExplorer.Hosting.csproj" />
    <ProjectReference Include="..\OakIdeas.Aspire.DataExplorer.Core\OakIdeas.Aspire.DataExplorer.Core.csproj" />
    <ProjectReference Include="..\OakIdeas.Aspire.DataExplorer.Contracts\OakIdeas.Aspire.DataExplorer.Contracts.csproj" />
    <ProjectReference Include="..\OakIdeas.Aspire.DataExplorer.Data\OakIdeas.Aspire.DataExplorer.Data.csproj" />
    <ProjectReference Include="..\OakIdeas.Aspire.DataExplorer.SqlServer\OakIdeas.Aspire.DataExplorer.SqlServer.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <Target Name="BuildTailwindCSS" BeforeTargets="Build" Condition="'$(NpmBuildEnabled)' != 'false'">
    <Exec Command="npm install" WorkingDirectory="$(MSBuildProjectDirectory)" />
    <Exec Command="npm run build:css" WorkingDirectory="$(MSBuildProjectDirectory)" />
  </Target>

</Project>
